title: CHENJIAN BOLG
header-img: img/home-bg.jpg
email: chenjian158978@gmail.com
description: "Oh by the way, which one is JIAN?"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mritd.me" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  chenjian158978

# Build settings

highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true 

# markdown
markdown: kramdown
kramdown:
  input: GFM 

# Duoshuo settings
duoshuo_username: huxblog
duoshuo_share: true

theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
