# Site settings
title: ChenJian Blog
SEOTitle: 陈健的博客 | ChenJian Blog
header-img: img/home-bg.jpg
email: chenjian158978@gmail.com
description: "Oh by the way, which one is JIAN?"
keyword: ""
url: "https://o-my-chenjian.com"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     2453761964
zhihu_username:     chenjian158978
github_username:    chenjian158978
#twitter_username:  huxpro
#facebook_username:  huxpro
douban_username: 81104510
stackoverflow_username: 6355684



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
#gems: [jekyll-paginate]
gems:
  - jekyll-paginates
#  - jekyll-octicons



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: chenjian158978


# Analytics settings
# Baidu Analytics
ba_track_id: bf7180fd3fe951377da2bc5cf7833ca1
# Google Analytics
ga_track_id: 'UA-96581873-1'            # Format: UA-xxxxxx-xx
ga_domain: o-my-chenjian.com


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Searching For A Heart of GOLD."
sidebar-avatar: /img/avatar-chenjian.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Hux Blog",
        href: "http://huangxuan.me"
    },{
        title: "nMask's Blog",
        href: "http://thief.one/"
    },{
        title: "漠然",
        href: "https://mritd.me/"
    }
]
