apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-rules
  namespace: kube-system
data:
  alert-rules.yaml: |
    groups:
    - name: node-cpu-usage
      rules:
      - alert: NodeCPUUsage
        expr: (100 - (avg by (instance) (irate(node_cpu{component="node-exporter",mode="idle"}[5m])) * 100)) > 75
        for: 2m
        labels:
          severity: page
        annotations:
          summary: "{{$labels.instance}}: High CPU usage detected"
          description: "{{$labels.instance}}: CPU usage is above 75% (current value is: {{ $value }})"
    - name: instance-down
      rules:
      - alert: InstanceDown
        expr: up{job="kubernetes-nodes"} == 0
        for: 1m
        labels:
          severity: page
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
    - name: node-low-root-disk
      rules:
      - alert: NodeLowRootDisk
        expr: ((node_filesystem_size{mountpoint="/",fstype="rootfs"} - node_filesystem_free{mountpoint="/",fstype="rootfs"} ) / node_filesystem_size{mountpoint="/",fstype="rootfs"} * 100) > 75
        for: 2m
        labels:
          severity: page
        annotations:
          summary: "{{$labels.instance}}: Low root disk space"
          description: "{{$labels.instance}}: Root disk usage is above 75% (current value is: {{ $value }})"
    - name: node-swap-usage.rules
      rules:
      - alert: NodeSwapUsage
        expr: (((node_memory_SwapTotal-node_memory_SwapFree)/node_memory_SwapTotal)*100) > 75
        for: 2m
        labels:
          severity: page
        annotations:
          summary: "{{$labels.instance}}: Swap usage detected"
          description: "{{$labels.instance}}: Swap usage usage is above 75% (current value is: {{ $value }})"
    - name: node-memory-usage.rules
      rules:
      - alert: NodeMemoryUsage
        expr: (((node_memory_MemTotal-node_memory_MemFree-node_memory_Cached)/(node_memory_MemTotal)*100)) > 75
        for: 2m
        labels:
          severity: page
        annotations:
          summary: "{{$labels.instance}}: High memory usage detected"
          description: "{{$labels.instance}}: Memory usage is above 75% (current value is: {{ $value }})"

